version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
      golang: latest
    commands:
      - mkdir ${TF_SETUP_DIR} && cd ${TF_SETUP_DIR}
      - "wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform_${TF_VERSION}_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
      - "chmod +x /usr/local/bin/terraform"
      - terraform --version
      - "rm -rf terraform_${TF_VERSION}_linux_amd64.zip"      
      - "yum update -y"
      - "yum -y --allowerasing install curl jq awscli"
      - "pip3 install checkov"
      - "yum install -y golang"
      - "wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64"
      - "chmod +x ./tfsec"
      - "mv ./tfsec /usr/local/bin/tfsec"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "echo ## VALIDATION : Starting ..."
      - "mkdir -p ${CODEBUILD_SRC_DIR}/reports"
      - "/bin/bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/tf_ssp_validation.sh ${SKIPVALIDATIONFAILURE} ${ENABLE_TFVALIDATE} ${ENABLE_TFFORMAT} ${ENABLE_TFCHECKOV} ${ENABLE_TFSEC}"
      - "cp checkov.xml ${CODEBUILD_SRC_DIR}/reports/checkov.xml"
      - "cp tfsec-junit.xml ${CODEBUILD_SRC_DIR}/reports/tfsec-junit.xml"
artifacts:
  files:
    - '**/*'
reports:
  bridgecrew-code-reports:
    files:
      - "./reports/checkov.xml"
    file-format: "JUNITXML"
  tfsec-code-reports:
    files:
      - "./reports/tfsec-junit.xml"
    file-format: "JUNITXML"