name: Create Release with Verion & Tags

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
          
  release-version-tags:
    name: Create Release with Version & Tags
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@aebba2bbce07a9474bf95e8710e5ee8a9e922fe2
        with:
          bump_version_scheme: major
          tag_prefix: v
          
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"